name: Create new version when pushing to master

on:
    push:
        branches:
            - master

jobs:
    bump_version:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
            - name: Bump version and push tag
              uses: ./
              env:
                GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
                REPO_OWNER: zyishai