name: Create new version when pushing to master

on:
    push:
        branches:
            - master

jobs:
    tag:
        name: Tag
        runs-on: ubuntu-latest
        steps:
            - name: Github Tag Bump
              uses: anothrNick/github-tag-action@1.19.0
              env:
                GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
                WITH_V: true
                RELEASE_BRANCHES: master